name: maturity_edition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pandas-datareader
  - requests
  - openpyxl
  - xlrd
  - pip
  - pip:
    - yfinance
    - fredapi